/* The following module borrows from mod_example.c but 
* is much simplified. Please see http://www.apache.org/LICENSE.txt 
* for the licence that mod_example.c and this module are licenced 
* under. All commentary on the module is included as 
* standard C style comments below */ 

/* All of these include files can be found in the Apache http source 
* tree in include/ . If you've got the Apache http server already 
* installed, then there will be an include directory either under the 
* directory that was specified with --prefix or somewhere in your 
* standard 
* include paths. All the functions that you can make use of can be 
* found 
* in the include files. */ 

#include "httpd.h" 
#include "http_config.h" 
#include "http_core.h" 
#include "http_log.h" 
#include "http_main.h" 
#include "http_protocol.h" 
#include "http_request.h" 
#include "util_script.h" 
#include "http_connection.h" 

#include <stdio.h>
#include <stdlib.h>
#include <string.h>


#include "lex.yy.c"
#include "y.tab.c"

/* read arbitray size file and return char star */
char *jsw_getline ( FILE *in )
{
    char buffer[BUFSIZ]; /* Buffer for partial lines */
    char *result = NULL; /* Buffer for the complete line */
    size_t size = 0;     /* Amount of memory assigned to result */

    /* In the average case, this should only run once */
    while ( fgets ( buffer, sizeof buffer, in ) != NULL ) {
        size_t len = strlen ( buffer );
        char *save = realloc ( result, size + len + 1 );

        /* If allocation fails, take what we've got */
        if ( save == NULL )
            break;

        /* Update the result buffer */
        strcpy ( save + size, buffer );
        result = save;
        size += len;

        /* Finish up if we found a newline */
        if ( result[size - 1] == '\n' ) {
            result[size - 1] = '\0';
            break;
        }
    }

    return result;
}

/* takes filename --> returns string of parsed text */
char * fuck(char *filename) {
    char * shit;

    /*
    FILE *fp;

    freopen("/tmp/out.txt", "a", stdout);

    parseFile(filename);

    freopen("/dev/tty", "a", stdout);

    fp=fopen("/tmp/out.txt", "r");

    shit = jsw_getline(fp);

    printf(shit);
    fclose(fp);
    */

//    strcpy(shit, "assholio!");

    return filename;
}

/* This example just takes a pointer to the request record as its only 
* argument */ 
static int webit_handler(request_rec *r) 
{ 

        /* We decline to handle a request if hello-handler is not the value 
         * of r->handler */ 
        if (strcmp(r->handler, "webit-handler")) { 
                return DECLINED; 
        } 

        /* The following line just prints a message to the errorlog */ 
        ap_log_error(APLOG_MARK, APLOG_NOERRNO|APLOG_NOTICE, 0, r->server, 
        "mod_webit: %s", "Loaded to kick ass!"); 

        /* We set the content type before doing anything else */ 
        ap_set_content_type(r, "text/html"); 

        /* If the request is for a header only, and not a request for 
         * the whole content, then return OK now. We don't have to do 
         * anything else. */ 
        if (r->header_only) { 
                return OK;
        } 

        /* Now we just print the contents of the document using the 
         * ap_rputs and ap_rprintf functions. More information about 
         * the use of these can be found in http_protocol.h */ 
        ap_rputs("<HTML>\n", r);
	ap_rputs("\t<HEAD>\n", r);
	ap_rputs("\t\t<TITLE>\n\t\t\tHello There\n\t\t</TITLE>\n", r);
	ap_rputs("\t</HEAD>\n\n", r);
	ap_rputs("<BODY BGCOLOR=\"#FFFFFF\">\n" ,r);
	ap_rputs("<H1>Hello </H1>\n", r);
	ap_rputs("Hello world\n", r);
	ap_rprintf(r, "<br>A sample line generated by ap_rprintf %s<br>\n", fuck(r->filename));
	ap_rputs("</BODY></HTML>\n" ,r); 

        /* We can either return OK or DECLINED at this point. If we return 
        * OK, then no other modules will attempt to process this request */ 
        return OK; 
}


/* Each function our module provides to handle a particular hook is 
* specified here. See mod_example.c for more information about this 
* step. Suffice to say that we need to list all of our handlers in 
* here. */ 
static void x_register_hooks(apr_pool_t *p) 
{ 
        ap_hook_handler(webit_handler, NULL, NULL, APR_HOOK_MIDDLE); 
}


/* Module definition for configuration. We list all callback routines 
* that we provide the static hooks into our module from the other parts 
* of the server. This list tells the server what function will handle a 
* particular type or stage of request. If we don't provide a function 
* to handle a particular stage / callback, use NULL as a placeholder as 
* illustrated below. */ 
module AP_MODULE_DECLARE_DATA webit_module = 
{ 
        STANDARD20_MODULE_STUFF, 
        NULL, /* per-directory config creator */ 
        NULL, /* directory config merger */ 
        NULL, /* server config creator */ 
        NULL, /* server config merger */ 
        NULL, /* command table */ 
        x_register_hooks, /* other request processing hooks */ 
};
